GET http://localhost:4000/api/user/users

###

POST http://localhost:4000/api/user/register
Content-Type: application/json

{
    "name":"ankijailwal",
    "email":"jailwalankit@gmail.com",
    "password":"may13s1993"
}

###

POST http://localhost:4000/api/user/login
Content-Type: application/json

{
    "name":"TestUser1",
    "password":"password"
}