GET http://localhost:3000/api/user/users

###

POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "name":"TestUser1",
    "password":"password"
}

###

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "name":"TestUser1",
    "password":"password"
}